-- ============================================================
-- V1 - Schema inicial (espelho do schema gerado pelo Hibernate)
-- ============================================================

-- Extensões necessárias (pg_dump não exporta extensões)
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ------------------------------------------------------------
-- Setores
-- ------------------------------------------------------------
CREATE TABLE sectors (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    CONSTRAINT uk_sectors_name UNIQUE (name)
);

-- ------------------------------------------------------------
-- Usuários
-- ------------------------------------------------------------
CREATE TABLE app_users (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username  VARCHAR(100) NOT NULL,
    password  VARCHAR(255) NOT NULL,
    enabled   BOOLEAN      NOT NULL,
    sector_id BIGINT       NOT NULL,
    CONSTRAINT uk_app_users_username UNIQUE (username),
    CONSTRAINT fk_app_users_sector FOREIGN KEY (sector_id) REFERENCES sectors (id)
);

CREATE INDEX idx_app_users_sector ON app_users (sector_id);

CREATE TABLE app_user_roles (
    user_id BIGINT      NOT NULL,
    role    VARCHAR(50),
    CONSTRAINT fk_app_user_roles_user FOREIGN KEY (user_id) REFERENCES app_users (id)
);

-- ------------------------------------------------------------
-- Conversas e mensagens
-- ------------------------------------------------------------
CREATE TABLE conversations (
    id         VARCHAR(255) PRIMARY KEY,
    user_id    VARCHAR(100) NOT NULL,
    title      VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL
);

CREATE TABLE chat_messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(255) NOT NULL,
    sender          VARCHAR(20)  NOT NULL,
    content         TEXT,
    status          VARCHAR(30),
    ticket_sector   VARCHAR(255),
    ticket_question VARCHAR(255),
    ticket_user_id  VARCHAR(255),
    created_at      TIMESTAMPTZ  NOT NULL,
    CONSTRAINT fk_chat_messages_conversation FOREIGN KEY (conversation_id)
        REFERENCES conversations (id)
);

CREATE TABLE chat_message_sources (
    message_id BIGINT NOT NULL,
    source     VARCHAR(255),
    CONSTRAINT fk_chat_message_sources_message FOREIGN KEY (message_id)
        REFERENCES chat_messages (id)
);

-- ------------------------------------------------------------
-- Documentos e controle de acesso
-- ------------------------------------------------------------
CREATE TABLE documents (
    id                     VARCHAR(255) PRIMARY KEY,
    filename               VARCHAR(255) NOT NULL,
    sector                 VARCHAR(255) NOT NULL,
    content_hash           VARCHAR(64)  NOT NULL,
    chunk_count            INTEGER      NOT NULL,
    ingested_at            TIMESTAMPTZ  NOT NULL,
    status                 VARCHAR(255) NOT NULL,
    supersedes_document_id VARCHAR(255),
    source_text            TEXT,
    CONSTRAINT uk_documents_content_hash UNIQUE (content_hash),
    CONSTRAINT ck_documents_status
        CHECK (status IN ('ACTIVE', 'SUPERSEDED', 'ARCHIVED'))
);

CREATE TABLE document_allowed_roles (
    document_id VARCHAR(255) NOT NULL,
    role        VARCHAR(50),
    CONSTRAINT fk_document_allowed_roles_document FOREIGN KEY (document_id)
        REFERENCES documents (id)
);

CREATE TABLE document_allowed_sectors (
    document_id VARCHAR(255) NOT NULL,
    sector_name VARCHAR(80)  NOT NULL,
    CONSTRAINT pk_document_allowed_sectors PRIMARY KEY (document_id, sector_name),
    CONSTRAINT fk_document_allowed_sectors_document FOREIGN KEY (document_id)
        REFERENCES documents (id)
);

CREATE INDEX idx_das_sector_name ON document_allowed_sectors (sector_name);

-- ------------------------------------------------------------
-- Conflitos entre documentos
-- ------------------------------------------------------------
CREATE TABLE conflict_candidates (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chunk_ida    VARCHAR(255)        NOT NULL,
    chunk_idb    VARCHAR(255)        NOT NULL,
    document_ida VARCHAR(255)        NOT NULL,
    document_idb VARCHAR(255)        NOT NULL,
    score        DOUBLE PRECISION    NOT NULL,
    snippeta     VARCHAR(500),
    snippetb     VARCHAR(500),
    status       VARCHAR(255)        NOT NULL,
    note         VARCHAR(500),
    detected_at  TIMESTAMPTZ         NOT NULL,
    updated_at   TIMESTAMPTZ,
    updated_by   VARCHAR(100),
    CONSTRAINT ck_conflict_candidates_status
        CHECK (status IN ('OPEN', 'REVIEWED', 'RESOLVED', 'DISMISSED'))
);

-- ------------------------------------------------------------
-- Base vetorial (Spring AI + pgvector)
-- ------------------------------------------------------------
CREATE TABLE vector_store (
    id        UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    content   TEXT,
    metadata  JSON,
    embedding VECTOR(1536)
);

CREATE INDEX spring_ai_vector_index
    ON vector_store USING hnsw (embedding vector_cosine_ops);